///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace sample1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the sample1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b662a334-97ca-4545-aa6a-9a321de8958b")]
    public partial class sample1Repository : RepoGenBaseFolder
    {
        static sample1Repository instance = new sample1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the sample1Repository element repository.
        /// </summary>
        [RepositoryFolder("b662a334-97ca-4545-aa6a-9a321de8958b")]
        public static sample1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public sample1Repository() 
            : base("sample1Repository", "/", null, 0, false, "b662a334-97ca-4545-aa6a-9a321de8958b", ".\\RepositoryImages\\sample1Repositoryb662a334.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b662a334-97ca-4545-aa6a-9a321de8958b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class sample1RepositoryFolders
    {
    }
#pragma warning restore 0436
}
